version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '8085:8085'
    volumes:
      - ./backend:/usr/src/backend
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/frontend